version: '3.3'

services:
  db:
  # db counter
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  web:
    # php apache content
    depends_on:
      - db
    image: php:apache
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - type: bind
        source: ./content/web/setup
        target: /setup
        read_only: true