version: '3.3'

services:
  db:
  # db counter
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: buttonclickerdb
      MYSQL_USER: buttonclick
      MYSQL_PASSWORD: buttonclick
  web:
    # php apache content
    depends_on:
      - db
    image: php:apache
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ./content/web/setup
        target: /setup
        read_only: true